YOLOV3:
  MODEL: "yolov3"
  CFG: "../yolov3/models/yolov3.yaml"
  WEIGHT: "../yolov3/runs/train/yolov3_saved/weights/best.pt"
  CLASS_NAMES: "./detector/YOLOv3/cfg/coco.names"
  HYP: "../yolov3/runs/train/yolov3_saved/hyp.yaml"
  SCORE_THRESH: 0.5
  NMS_THRESH: 0.4
