YOLOV4:
  MODEL: "yolov4"

  CFG: "../yolov4_new/models/yolov4-pacsp.cfg"
  WEIGHT: "../yolov4_new/runs/train/yolov4_saved/weights/best.pt"
  CLASS_NAMES: "./detector/YOLOv3/cfg/coco.names"
  HYP: "../yolov4_new/runs/train/yolov4_saved/hyp.yaml"

  SCORE_THRESH: 0.5
  NMS_THRESH: 0.4
