YOLOV4:
  MODEL: "yolov4"

  CFG: "../yolov4/models/yolov4-csp-x-mish.cfg"
  WEIGHT: "../yolov4/runs/train/yolov4_saved/weights/me.pt"
  CLASS_NAMES: "./detector/YOLOv3/cfg/coco.names"
  HYP: "../yolov4/runs/train/yolov4_saved/hyp.yaml"

  SCORE_THRESH: 0.5
  NMS_THRESH: 0.4
